In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(r'df_raw.csv')
df

Unnamed: 0  Reson_1  Reason_2  Reason_3  Reason_4  Month value  \
0             0        0         0         0         1            7   
1             1        0         0         0         0            7   
2             2        0         0         0         1            7   
3             3        1         0         0         0            7   
4             4        0         0         0         1            7   
..          ...      ...       ...       ...       ...          ...   
695         695        1         0         0         0            5   
696         696        1         0         0         0            5   
697         697        1         0         0         0            5   
698         698        0         0         0         1            5   
699         699        0         0         0         1            5   

     Day of the week  Transportation Expense  Distance to Work  Age  \
0                  1                     289                36   33   
1                  1                     118                13   50   
2                  2                     179                51   38   
3                  3                     279                 5   39   
4                  3                     289                36   33   
..               ...                     ...               ...  ...   
695                2                     179                22   40   
696                2                     225                26   28   
697                3                     330                16   28   
698                3                     235                16   32   
699                3                     291                31   40   

     Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                    239.554               30          0         2     1   
1                    239.554               31          0         1     0   
2                    239.554               31          0         0     0   
3                    239.554               24          0         2     0   
4                    239.554               30          0         2     1   
..                       ...              ...        ...       ...   ...   
695                  237.656               22          1         2     0   
696                  237.656               24          0         1     2   
697                  237.656               25          1         0     0   
698                  237.656               25          1         0     0   
699                  237.656               25          0         1     1   

     Absenteeism Time in Hours  
0                            4  
1                            0  
2                            2  
3                            4  
4                            2  
..                         ...  
695                          8  
696                          3  
697                          8  
698                          2  
699                          2  

[700 rows x 16 columns]

In [3]:
df['Absenteeism Time in Hours'].median()

3.0

In [4]:
targets=np.where(df['Absenteeism Time in Hours']>
                df['Absenteeism Time in Hours'].median(),1,0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [5]:
df['Excessive Absenteeism']=targets
df.head(5)

Unnamed: 0  Reson_1  Reason_2  Reason_3  Reason_4  Month value  \
0           0        0         0         0         1            7   
1           1        0         0         0         0            7   
2           2        0         0         0         1            7   
3           3        1         0         0         0            7   
4           4        0         0         0         1            7   

   Day of the week  Transportation Expense  Distance to Work  Age  \
0                1                     289                36   33   
1                1                     118                13   50   
2                2                     179                51   38   
3                3                     279                 5   39   
4                3                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          0         2     1   
1                  239.554               31          0         1     0   
2                  239.554               31          0         0     0   
3                  239.554               24          0         2     0   
4                  239.554               30          0         2     1   

   Absenteeism Time in Hours  Excessive Absenteeism  
0                          4                      1  
1                          0                      0  
2                          2                      0  
3                          4                      1  
4                          2                      0

In [6]:
targets.sum()/targets.shape[0]

0.45571428571428574

In [7]:
df_with_targets=df.drop(['Absenteeism Time in Hours','Day of the week','Daily Work Load Average','Distance to Work'],axis=1)
df_with_targets is df

False

In [8]:
df_with_targets.iloc[:,:-1]
df_with_targets.head(5)

Unnamed: 0  Reson_1  Reason_2  Reason_3  Reason_4  Month value  \
0           0        0         0         0         1            7   
1           1        0         0         0         0            7   
2           2        0         0         0         1            7   
3           3        1         0         0         0            7   
4           4        0         0         0         1            7   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                     289   33               30          0         2     1   
1                     118   50               31          0         1     0   
2                     179   38               31          0         0     0   
3                     279   39               24          0         2     0   
4                     289   33               30          0         2     1   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [9]:
df_with_targets.columns.values

array(['Unnamed: 0', 'Reson_1', 'Reason_2', 'Reason_3', 'Reason_4',
       'Month value', 'Transportation Expense', 'Age', 'Body Mass Index',
       'Education', 'Children', 'Pets', 'Excessive Absenteeism'],
      dtype=object)

In [10]:
columns_names=(['Unnamed: 0', 'Reson_1', 'Reason_2', 'Reason_3', 'Reason_4',
       'Month value', 'Transportation Expense', 'Age', 'Body Mass Index',
       'Education', 'Children', 'Pets', 'Excessive Absenteeism'])

In [11]:
columns_names_reordered=(['Unnamed: 0', 'Reson_1', 'Reason_2', 'Reason_3', 'Reason_4',
       'Month value', 'Transportation Expense', 'Age', 'Body Mass Index',
       'Education', 'Children', 'Pets', 'Excessive Absenteeism'])

In [12]:
df_pro=df[columns_names_reordered]
df_pro.head(6)

Unnamed: 0  Reson_1  Reason_2  Reason_3  Reason_4  Month value  \
0           0        0         0         0         1            7   
1           1        0         0         0         0            7   
2           2        0         0         0         1            7   
3           3        1         0         0         0            7   
4           4        0         0         0         1            7   
5           5        0         0         0         1           10   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                     289   33               30          0         2     1   
1                     118   50               31          0         1     0   
2                     179   38               31          0         0     0   
3                     279   39               24          0         2     0   
4                     289   33               30          0         2     1   
5                     179   38               31          0         0     0   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0  
5                      0

In [13]:
unscaled_inputs=df_pro.iloc[:,:-1]

In [14]:
from sklearn.base import BaseEstimator,TransformerMixin
from sklearn.preprocessing import StandardScaler
class CustomScaler(BaseEstimator,TransformerMixin):
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        self.scaler=StandardScaler(copy,with_mean,with_std)
        self.columns=columns
        self.mean_=None
        self.var_=None
        
    def fit(self,x,y=None):
        self.scaler.fit(x[self.columns],y)
        self.mean_=np.mean(x[self.columns])
        self.var_=np.var(x[self.columns])
        return self
        
    def transform(self,x,y=None,copy=None):
        init_col_order=x.columns
        x_scaled=pd.DataFrame(self.scaler.transform(x[self.columns]),columns=self.columns)
        x_not_scaled=x.loc[:,~x.columns.isin(self.columns)]
        return pd.concat([x_not_scaled,x_scaled],axis=1)[init_col_order]
        

In [15]:
unscaled_inputs.columns.values

array(['Unnamed: 0', 'Reson_1', 'Reason_2', 'Reason_3', 'Reason_4',
       'Month value', 'Transportation Expense', 'Age', 'Body Mass Index',
       'Education', 'Children', 'Pets'], dtype=object)

In [16]:
columns_to_omit=['Reason_1','Reason_2','Reason_3','Reason_4','Education']

In [17]:
columns_to_scale=[x for x in unscaled_inputs.columns.values]

In [18]:
absenteeism_scaler=CustomScaler(columns_to_scale)

In [19]:
absenteeism_scaler.fit(unscaled_inputs)

C:\Users\HP\anaconda3\lib\site-packages\sklearn\base.py:197: FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
  FutureWarning)


CustomScaler(columns=['Unnamed: 0', 'Reson_1', 'Reason_2', 'Reason_3',
                      'Reason_4', 'Month value', 'Transportation Expense',
                      'Age', 'Body Mass Index', 'Education', 'Children',
                      'Pets'],
             copy=None, with_mean=None, with_std=None)

In [20]:
scaled_inputs=absenteeism_scaler.transform(unscaled_inputs)

In [21]:
scaled_inputs

Unnamed: 0   Reson_1  Reason_2  Reason_3  Reason_4  Month value  \
0     -1.729578 -0.577350 -0.092981 -0.314485  0.821365     0.030796   
1     -1.724629 -0.577350 -0.092981 -0.314485 -1.217485     0.030796   
2     -1.719681 -0.577350 -0.092981 -0.314485  0.821365     0.030796   
3     -1.714732  1.732051 -0.092981 -0.314485 -1.217485     0.030796   
4     -1.709783 -0.577350 -0.092981 -0.314485  0.821365     0.030796   
..          ...       ...       ...       ...       ...          ...   
695    1.709783  1.732051 -0.092981 -0.314485 -1.217485    -0.568019   
696    1.714732  1.732051 -0.092981 -0.314485 -1.217485    -0.568019   
697    1.719681  1.732051 -0.092981 -0.314485 -1.217485    -0.568019   
698    1.724629 -0.577350 -0.092981 -0.314485  0.821365    -0.568019   
699    1.729578 -0.577350 -0.092981 -0.314485  0.821365    -0.568019   

     Transportation Expense       Age  Body Mass Index  Education  Children  \
0                  1.005844 -0.536062         0.767431  -0.447980  0.880469   
1                 -1.574681  2.130803         1.002633  -0.447980 -0.019280   
2                 -0.654143  0.248310         1.002633  -0.447980 -0.919030   
3                  0.854936  0.405184        -0.643782  -0.447980  0.880469   
4                  1.005844 -0.536062         0.767431  -0.447980  0.880469   
..                      ...       ...              ...        ...       ...   
695               -0.654143  0.562059        -1.114186   2.232242  0.880469   
696                0.040034 -1.320435        -0.643782  -0.447980 -0.019280   
697                1.624567 -1.320435        -0.408580   2.232242 -0.919030   
698                0.190942 -0.692937        -0.408580   2.232242 -0.919030   
699                1.036026  0.562059        -0.408580  -0.447980 -0.019280   

         Pets  
0    0.268487  
1   -0.589690  
2   -0.589690  
3   -0.589690  
4    0.268487  
..        ...  
695 -0.589690  
696  1.126663  
697 -0.589690  
698 -0.589690  
699  0.268487  

[700 rows x 12 columns]

In [22]:
scaled_inputs.shape

(700, 12)

In [23]:
from sklearn.model_selection import train_test_split

train_test_split(scaled_inputs,targets)

[     Unnamed: 0   Reson_1   Reason_2  Reason_3  Reason_4  Month value  \
 247   -0.507244 -0.577350  -0.092981 -0.314485  0.821365     0.030796   
 689    1.680091 -0.577350  -0.092981 -0.314485  0.821365    -0.568019   
 668    1.576168 -0.577350  10.754844 -0.314485 -1.217485    -0.867426   
 298   -0.254859 -0.577350  -0.092981 -0.314485  0.821365     0.929019   
 470    0.596321 -0.577350  -0.092981 -0.314485  0.821365     0.030796   
 ..          ...       ...        ...       ...       ...          ...   
 582    1.150578  1.732051  -0.092981 -0.314485 -1.217485    -1.765648   
 339   -0.051962  1.732051  -0.092981 -0.314485 -1.217485    -0.568019   
 364    0.071756  1.732051  -0.092981 -0.314485 -1.217485     1.228426   
 337   -0.061859 -0.577350  -0.092981 -0.314485 -1.217485     1.228426   
 398    0.240013 -0.577350  -0.092981 -0.314485  0.821365    -1.166834   
 
      Transportation Expense       Age  Body Mass Index  Education  Children  \
 247                1.005844 -

In [24]:
x_train,x_test,y_train,y_test=train_test_split(scaled_inputs,targets,train_size=0.8,random_state=20)
print(x_train.shape,y_train.shape)

(560, 12) (560,)


In [25]:
print(x_test.shape,y_test.shape)

(140, 12) (140,)


In [26]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [27]:
reg=LogisticRegression()
reg.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [28]:
reg.score(x_train,y_train)

0.7821428571428571

In [29]:
model_outputs=reg.predict(x_train)
model_outputs==y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
       False,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [30]:
np.sum((model_outputs==y_train))

438

In [31]:
model_outputs.shape[0]

560

In [32]:
np.sum((model_outputs==y_train))/model_outputs.shape[0]

0.7821428571428571

In [33]:
reg.intercept_

array([-0.22196249])

In [34]:
reg.coef_

array([[-0.24049947,  2.07418627,  0.34319121,  1.53283066,  1.31173823,
         0.00808223,  0.70122041, -0.1872034 ,  0.34875936, -0.08049887,
         0.36705487, -0.30437267]])

In [35]:
unscaled_inputs.columns.values

array(['Unnamed: 0', 'Reson_1', 'Reason_2', 'Reason_3', 'Reason_4',
       'Month value', 'Transportation Expense', 'Age', 'Body Mass Index',
       'Education', 'Children', 'Pets'], dtype=object)

In [36]:
feature_name=unscaled_inputs.columns.values

In [37]:
summary_table=pd.DataFrame(columns=['feature_name'],data=feature_name)
summary_table['coefficient']=np.transpose(reg.coef_)
summary_table

feature_name  coefficient
0               Unnamed: 0    -0.240499
1                  Reson_1     2.074186
2                 Reason_2     0.343191
3                 Reason_3     1.532831
4                 Reason_4     1.311738
5              Month value     0.008082
6   Transportation Expense     0.701220
7                      Age    -0.187203
8          Body Mass Index     0.348759
9                Education    -0.080499
10                Children     0.367055
11                    Pets    -0.304373

In [38]:
summary_table.index=summary_table.index+1
summary_table.loc[0]=['Intercept',reg.intercept_[0]]
summary_table=summary_table.sort_index()
summary_table

feature_name  coefficient
0                Intercept    -0.221962
1               Unnamed: 0    -0.240499
2                  Reson_1     2.074186
3                 Reason_2     0.343191
4                 Reason_3     1.532831
5                 Reason_4     1.311738
6              Month value     0.008082
7   Transportation Expense     0.701220
8                      Age    -0.187203
9          Body Mass Index     0.348759
10               Education    -0.080499
11                Children     0.367055
12                    Pets    -0.304373

In [39]:
summary_table['Odds_ratio']=np.exp(summary_table.coefficient)
summary_table

feature_name  coefficient  Odds_ratio
0                Intercept    -0.221962    0.800945
1               Unnamed: 0    -0.240499    0.786235
2                  Reson_1     2.074186    7.958068
3                 Reason_2     0.343191    1.409438
4                 Reason_3     1.532831    4.631268
5                 Reason_4     1.311738    3.712621
6              Month value     0.008082    1.008115
7   Transportation Expense     0.701220    2.016212
8                      Age    -0.187203    0.829275
9          Body Mass Index     0.348759    1.417308
10               Education    -0.080499    0.922656
11                Children     0.367055    1.443477
12                    Pets    -0.304373    0.737586

In [40]:
summary_table.sort_values('Odds_ratio',ascending=False)

feature_name  coefficient  Odds_ratio
2                  Reson_1     2.074186    7.958068
4                 Reason_3     1.532831    4.631268
5                 Reason_4     1.311738    3.712621
7   Transportation Expense     0.701220    2.016212
11                Children     0.367055    1.443477
9          Body Mass Index     0.348759    1.417308
3                 Reason_2     0.343191    1.409438
6              Month value     0.008082    1.008115
10               Education    -0.080499    0.922656
8                      Age    -0.187203    0.829275
0                Intercept    -0.221962    0.800945
1               Unnamed: 0    -0.240499    0.786235
12                    Pets    -0.304373    0.737586

In [41]:
reg.score(x_test,y_test)

0.7357142857142858

In [42]:
predicted_proba=reg.predict_proba(x_test)
predicted_proba

array([[0.79357328, 0.20642672],
       [0.5850148 , 0.4149852 ],
       [0.43606252, 0.56393748],
       [0.81674641, 0.18325359],
       [0.04892338, 0.95107662],
       [0.34653069, 0.65346931],
       [0.21827753, 0.78172247],
       [0.10692206, 0.89307794],
       [0.69944632, 0.30055368],
       [0.67563513, 0.32436487],
       [0.53434399, 0.46565601],
       [0.1807959 , 0.8192041 ],
       [0.03545013, 0.96454987],
       [0.70800603, 0.29199397],
       [0.26203283, 0.73796717],
       [0.50655634, 0.49344366],
       [0.57981857, 0.42018143],
       [0.45157596, 0.54842404],
       [0.43829549, 0.56170451],
       [0.03992805, 0.96007195],
       [0.69007466, 0.30992534],
       [0.81638987, 0.18361013],
       [0.46031707, 0.53968293],
       [0.46086915, 0.53913085],
       [0.23634698, 0.76365302],
       [0.72812724, 0.27187276],
       [0.54291142, 0.45708858],
       [0.90678084, 0.09321916],
       [0.20892519, 0.79107481],
       [0.81745787, 0.18254213],
       [0.

In [43]:
predicted_proba.shape

(140, 2)

In [44]:
predicted_proba[:,1]

array([0.20642672, 0.4149852 , 0.56393748, 0.18325359, 0.95107662,
       0.65346931, 0.78172247, 0.89307794, 0.30055368, 0.32436487,
       0.46565601, 0.8192041 , 0.96454987, 0.29199397, 0.73796717,
       0.49344366, 0.42018143, 0.54842404, 0.56170451, 0.96007195,
       0.30992534, 0.18361013, 0.53968293, 0.53913085, 0.76365302,
       0.27187276, 0.45708858, 0.09321916, 0.79107481, 0.18254213,
       0.30056435, 0.76715544, 0.76036891, 0.45680334, 0.1823646 ,
       0.6798143 , 0.19755912, 0.86454088, 0.43590873, 0.70166095,
       0.18919922, 0.43697732, 0.28186409, 0.10816547, 0.82039471,
       0.65434646, 0.65689901, 0.3063637 , 0.22939176, 0.19361379,
       0.4435076 , 0.07010611, 0.76548503, 0.20645378, 0.88578727,
       0.40464177, 0.91720646, 0.19450519, 0.08504429, 0.08385112,
       0.65244649, 0.66816602, 0.21707055, 0.87178825, 0.27355334,
       0.31429371, 0.01138983, 0.29459979, 0.81249549, 0.39732194,
       0.29035569, 0.08561   , 0.91229169, 0.41004317, 0.58355

In [45]:
import pickle

In [46]:
with open('Absenteeism','wb')as file:
    pickle.dump(reg,file)

In [47]:
with open('scaler','wb')as file:
    pickle.dump(absenteeism_scaler,file)